# Generated by Django 5.0.6 on 2024-06-23 08:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id_client', models.IntegerField(primary_key=True, serialize=False)),
                ('name_client', models.CharField(max_length=100)),
                ('second_name_client', models.CharField(max_length=100)),
                ('id_user', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='logining.client')),
                ('email_user', models.EmailField(max_length=254)),
                ('password_user', models.CharField(max_length=250)),
                ('tag_user', models.CharField(max_length=100)),
            ],
        ),
    ]
