# Generated by Django 5.0.6 on 2024-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logining', '0002_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_user',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
