# Generated by Django 5.0.6 on 2024-06-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logining', '0004_alter_client_id_user_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='id_client',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.IntegerField(db_index=True, primary_key=True, serialize=False),
        ),
    ]
