# Generated by Django 5.0.6 on 2024-06-23 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logining', '0005_alter_client_id_client_alter_user_id_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-id_client'], 'verbose_name': 'Клиент'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-id_user'], 'verbose_name': 'Пользователи'},
        ),
    ]
