# Generated by Django 5.0.6 on 2024-06-23 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logining', '0006_alter_client_options_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.CharField(choices=[('Не в работе', 'Не в работе'), ('В архиве', 'В архиве'), ('В работе', 'В работе')], default='Не в работе', max_length=40),
        ),
    ]
